tries = ["lobby"]

[servers]
lobby = "localhost:25565"
[logging]
errors = false
pings = true
commands = true
[settings]
motd = "A LavaProxy proxy.<newline>Total connections: {conAmount}"
port = 25577
[server-settings]
forward-mode = "none" # none, bungeecord (ip forward), bungeeguard (forward-key)
forward-key = "" # use for bungeeguard